#!/bin/bash
used=$((`df /dev/vg0/root | awk '{print $3}' | sed -n '2p'`))
newused=$(bc <<< "scale=2; $used/1000000")
total=$((`df /dev/vg0/root | awk '{print $4}' | sed -n '2p'`))
newtotal=$(bc <<< "scale=2; $total/1000000")
echo "$newused / $newtotal GB"
